version: "3.9"

# x-airflow-common: &airflow-common
#   image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.3}
#   env_file:
#     - ./.env
#   environment: &airflow-common-env
#     AIRFLOW__CORE__EXECUTOR: CeleryExecutor
#     AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
#     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN:-postgresql+psycopg2://airflow:airflow@postgres-db/airflow}
#     AIRFLOW__CELERY__RESULT_BACKEND: ${AIRFLOW_CELERY_RESULT_BACKEND:-db+postgresql://airflow:airflow@postgres-db/airflow}
#     AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW_CELERY_BROKER_URL:-redis://:@redis:6379/0}
#     AIRFLOW__CORE__FERNET_KEY: ""
#     AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
#     AIRFLOW__CORE__LOAD_EXAMPLES: "true"
#     AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
#     AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
#     _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
#     AIRFLOW_CONFIG: "/opt/airflow/config/airflow.cfg"
#   volumes:
#     - ./airflow/dags:/opt/airflow/dags
#     - ./airflow/logs:/opt/airflow/logs
#     - ./airflow/config:/opt/airflow/config
#     - ./airflow/plugins:/opt/airflow/plugins
#   user: "${AIRFLOW_UID:-50000}:0"
#   depends_on: &airflow-common-depends-on
#     redis:
#       condition: service_healthy
#     postgres-db:
#       condition: service_healthy
#   deploy:
#     resources:
#       limits:
#         cpus: "1"
#         memory: 2G
#   logging:
#     driver: "json-file"
#     options:
#       max-size: "10m"
#       max-file: "3"
#   networks:
#     - data-platform-net

services:

  postgres-db:
    image: postgres:18
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql
      - ./backend/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    env_file:
      - ./backend/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - data-platform-net

  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - data-platform-net

  db-migrator:
    build: ./backend/db/migrations
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - ./backend/logging.env
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    volumes:
      - ./backend/seeds/seed.sql:/app/seed.sql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - data-platform-net

  pgadmin:
    image: dpage/pgadmin4:9
    restart: always
    env_file:
      - ./backend/db/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - data-platform-net

  flinkjobmanager:
    build: ./streaming/flink-java
    image: graduation-project-flinkjobmanager
    command: [ "jobmanager" ]
    ports:
      - "8081:8081"
      - "9249:9249"
    depends_on:
      - postgres-db
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - data-platform-net

  flinktaskmanager:
    build: ./streaming/flink-java
    image: graduation-project-flinktaskmanager
    command: [ "taskmanager" ]
    depends_on:
      - flinkjobmanager
      - postgres-db
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - data-platform-net

volumes:
  pgdata:
  pgadmin-data:
  kafka-data:
  postgres-db-volume:
  minio-data:
  clickhouse-data:

networks:
  data-platform-net:
    driver: bridge
