FROM python:3.11-slim

WORKDIR /app

# Pin versions (stable + reproducible)
RUN pip install --no-cache-dir kafka-python==2.3.0 requests==2.32.5

COPY consumer_service.py /app/consumer_service.py

ENV PYTHONUNBUFFERED=1

CMD ["python", "-u", "consumer_service.py"]
