ALTER TABLE entry_logs
ADD COLUMN IF NOT EXISTS quality_score DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS best_similarity DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS second_similarity DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS margin DOUBLE PRECISION;

ALTER TABLE unknown_face_events
ADD COLUMN IF NOT EXISTS quality_score DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS best_similarity DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS second_similarity DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS margin DOUBLE PRECISION;